# Generated by Django 5.1.5 on 2025-03-28 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_user_balance_alter_item_price_alter_item_stock_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
